import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const customFont = Kanit({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={customFont.className}>
      <body className="p-2 md:p-5">{children}</body>
    </html>
  );
}
